export const productsSeed = [
  {
    name: 'Wireless Keyboard',
    description: 'Compact mechanical keyboard with RGB lighting.',
    price: 79.99,
    stock: 25,
    category: 'electronics',
    images: ['uploads/products/keyboard.jpg'],
    isActive: true,
  },
  {
    name: 'Noise Cancelling Headphones',
    description: 'Over-ear headphones with active noise cancellation.',
    price: 129.99,
    stock: 40,
    category: 'electronics',
    images: ['uploads/products/headphones.jpg'],
    isActive: true,
  },
  {
    name: 'Organic Cotton T-Shirt',
    description: 'Comfortable and eco-friendly cotton t-shirt.',
    price: 19.99,
    stock: 100,
    category: 'apparel',
    images: ['uploads/products/tshirt.jpg'],
    isActive: true,
  },

  // Added 20 products
  {
    name: 'Gaming Mouse',
    description: 'High precision wireless gaming mouse.',
    price: 49.99,
    stock: 60,
    category: 'electronics',
    images: ['uploads/products/mouse.jpg'],
    isActive: true,
  },
  {
    name: 'Bluetooth Speaker',
    description: 'Portable speaker with deep bass.',
    price: 59.99,
    stock: 30,
    category: 'electronics',
    images: ['uploads/products/speaker.jpg'],
    isActive: true,
  },
  {
    name: 'Smart Watch',
    description: 'Fitness tracking smartwatch with heart rate monitor.',
    price: 149.99,
    stock: 20,
    category: 'electronics',
    images: ['uploads/products/smartwatch.jpg'],
    isActive: true,
  },
  {
    name: 'Laptop Stand',
    description: 'Ergonomic aluminum laptop stand.',
    price: 34.99,
    stock: 50,
    category: 'electronics',
    images: ['uploads/products/laptop-stand.jpg'],
    isActive: true,
  },
  {
    name: 'USB-C Hub',
    description: 'Multi-port USB-C adapter.',
    price: 29.99,
    stock: 70,
    category: 'electronics',
    images: ['uploads/products/usb-hub.jpg'],
    isActive: true,
  },
  {
    name: 'Running Shoes',
    description: 'Lightweight and comfortable running shoes.',
    price: 89.99,
    stock: 45,
    category: 'apparel',
    images: ['uploads/products/shoes.jpg'],
    isActive: true,
  },
  {
    name: 'Denim Jeans',
    description: 'Slim fit stretch denim jeans.',
    price: 49.99,
    stock: 80,
    category: 'apparel',
    images: ['uploads/products/jeans.jpg'],
    isActive: true,
  },
  {
    name: 'Hoodie Sweatshirt',
    description: 'Warm fleece hoodie.',
    price: 39.99,
    stock: 65,
    category: 'apparel',
    images: ['uploads/products/hoodie.jpg'],
    isActive: true,
  },
  {
    name: 'Baseball Cap',
    description: 'Adjustable casual cap.',
    price: 14.99,
    stock: 120,
    category: 'apparel',
    images: ['uploads/products/cap.jpg'],
    isActive: true,
  },
  {
    name: 'Leather Wallet',
    description: 'Premium leather wallet with RFID protection.',
    price: 24.99,
    stock: 55,
    category: 'accessories',
    images: ['uploads/products/wallet.jpg'],
    isActive: true,
  },
  {
    name: 'Sunglasses',
    description: 'UV protection stylish sunglasses.',
    price: 29.99,
    stock: 75,
    category: 'accessories',
    images: ['uploads/products/sunglasses.jpg'],
    isActive: true,
  },
  {
    name: 'Backpack',
    description: 'Durable backpack for daily use.',
    price: 54.99,
    stock: 35,
    category: 'accessories',
    images: ['uploads/products/backpack.jpg'],
    isActive: true,
  },
  {
    name: 'Water Bottle',
    description: 'Insulated stainless steel bottle.',
    price: 19.99,
    stock: 90,
    category: 'home',
    images: ['uploads/products/bottle.jpg'],
    isActive: true,
  },
  {
    name: 'Desk Lamp',
    description: 'LED desk lamp with adjustable brightness.',
    price: 22.99,
    stock: 40,
    category: 'home',
    images: ['uploads/products/lamp.jpg'],
    isActive: true,
  },
  {
    name: 'Coffee Maker',
    description: 'Automatic drip coffee maker.',
    price: 79.99,
    stock: 15,
    category: 'home',
    images: ['uploads/products/coffee-maker.jpg'],
    isActive: true,
  },
  {
    name: 'Electric Kettle',
    description: 'Fast boiling electric kettle.',
    price: 34.99,
    stock: 25,
    category: 'home',
    images: ['uploads/products/kettle.jpg'],
    isActive: true,
  },
  {
    name: 'Yoga Mat',
    description: 'Non-slip exercise yoga mat.',
    price: 25.99,
    stock: 60,
    category: 'fitness',
    images: ['uploads/products/yoga-mat.jpg'],
    isActive: true,
  },
  {
    name: 'Dumbbell Set',
    description: 'Adjustable weight dumbbells.',
    price: 99.99,
    stock: 20,
    category: 'fitness',
    images: ['uploads/products/dumbbells.jpg'],
    isActive: true,
  },
  {
    name: 'Skipping Rope',
    description: 'Speed rope for cardio workouts.',
    price: 9.99,
    stock: 150,
    category: 'fitness',
    images: ['uploads/products/rope.jpg'],
    isActive: true,
  },
  {
    name: 'Protein Shaker',
    description: 'Leak-proof shaker bottle.',
    price: 12.99,
    stock: 110,
    category: 'fitness',
    images: ['uploads/products/shaker.jpg'],
    isActive: true,
  },
];
